### ISSUE TITLE
Tracking Upstream

### ISSUE THREAD

**Issue by claudioperez** [claudioperez/OpenSeesRT#31]
- [ ] https://github.com/OpenSees/OpenSees/commit/cbdfe3969c4b096ced94accad0e79fd1f52b901e Damping
- [ ] https://github.com/OpenSees/OpenSees/pull/1168
- [ ] https://github.com/OpenSees/OpenSees/pull/845
- [ ] https://github.com/OpenSees/OpenSees/commit/df8dbc5bbe2ffb6ffe213c4b3018f1c8209f7672
- [ ] https://github.com/OpenSees/OpenSees/commit/ed48fd47b40c22e278b23dca05fb4ce75ed13945
- [ ] https://github.com/claudioperez/OpenSees-Upstream/commit/b0a7b13348ca3b49b39d77111005f7446b597b7a
- [ ] https://github.com/OpenSees/OpenSees/commit/2bbf460870d4ba57fa7b27c4384534a9b0a5c29a (BoucWen)
- [ ] https://github.com/OpenSees/OpenSees/commit/e455e6214517fead95f67c7383280d4c56865caf
- [ ] https://github.com/OpenSees/OpenSees/pull/1312
- [ ] https://github.com/OpenSees/OpenSees/pull/1330
