### ISSUE TITLE
Tracking Upstream: Materials

### ISSUE THREAD

**Issue by claudioperez** [claudioperez/OpenSeesRT#38]
- [ ] `SRC/material/nD/ElasticOrthotropicPlaneStress.cpp`
- [ ] `SRC/material/nD/ElasticOrthotropicPlaneStress.h`
- [ ] `SRC/material/nD/OrthotropicMaterial.cpp`
- [ ] `SRC/material/nD/OrthotropicMaterial.h`
- [ ] `SRC/material/nD/Series3DMaterial.cpp`
- [ ] `SRC/material/nD/Series3DMaterial.h`
- [ ] `SRC/material/uniaxial/CreepMaterial.cpp`
- [ ] `SRC/material/uniaxial/CreepMaterial.h`
- [ ] `SRC/material/uniaxial/FRCC.cpp`
- [ ] `SRC/material/uniaxial/FRCC.h`
- [ ] `SRC/material/uniaxial/GMG_CyclicReinforcedConcrete.cpp`
- [ ] `SRC/material/uniaxial/GMG_CyclicReinforcedConcrete.h`
- [ ] `SRC/material/uniaxial/HystereticAsym.cpp`
- [ ] `SRC/material/uniaxial/HystereticAsym.h`
- [ ] `SRC/material/uniaxial/HystereticSmooth.cpp`
- [ ] `SRC/material/uniaxial/HystereticSmooth.h`
- [ ] `SRC/material/uniaxial/JankowskiImpact.cpp`
- [ ] `SRC/material/uniaxial/JankowskiImpact.h`
- [ ] `SRC/material/uniaxial/ViscoelasticGap.cpp`
- [ ] `SRC/material/uniaxial/ViscoelasticGap.h`
- [ ] `SRC/material/uniaxial/TDConcreteNL.cpp`
- [ ] `SRC/material/uniaxial/TDConcreteNL.h`
